### ISSUE TITLE
RQProc seems to make an excessive # of calls to redis in `quantity`

### ISSUE THREAD

**Issue by ryanisnan** [ryanhiebert/hirefire#12]
I'm observing a large number of HGET redis calls (664 in 1 instance) during a call to `RQProc.quantity`.

Here's the exact method: https://github.com/jezdez/hirefire/blob/master/hirefire/procs/rq.py#L53

I'm guessing that it has something to do with nested iterators? I wonder if it's more sensible to just look at `queue.count` and ignore jobs in process?

**Comment by adamlwgriffiths** [comment]
This code was added in 0.2.1.
https://github.com/jezdez/hirefire/commit/d8136b4557978d9a22874c1423524bb8b3b68c63
Quote from change log: "Fix the RQ Proc implementation to take the number of task into account that are currently being processed by the workers to prevent accidental shutdown mid-processing. Thanks to Jason Lantz for the report and initial patch."

Looks like calling `get_current_job_id` might suffice too, and avoid any further logic, as `get_current_job`  calls `get_current_job_id` first then instantiates a job object. It's still an HGET per active job, I'm not sure if Job instantiation does any more.

There may be a better function to call to query active jobs, but without understanding RQ further thats the best I can provide.

**Comment by ryanhiebert** [comment]
I had a similar issue with Celery as prompted the issue mentioned in 0.2.1. I think that correctness needs to be first, and that any compromise for speed must be optional and non-default. I would be happy to see such a patch for RQ. Take a look at the proc settings I added for #13 for inspiration. I don't have any current plans to work on it myself.
