### ISSUE TITLE
Django Channels

### ISSUE THREAD

**Issue by ryanhiebert** [ryanhiebert/hirefire#14]
Django Channels introduce a `django-admin runworker` command, which will actually run the normal Django code, but in a worker process. HireFire should support auto-scaling those procs.

**Comment by jezdez** [comment]
That's a great idea!

**Comment by jezdez** [comment]
@ryanhiebert Would you be interested in being added to the hirefire project?

**Comment by ryanhiebert** [comment]
Yes, absolutely!

**Comment by ryanhiebert** [comment]
I'm still learning about channels, and I haven't figured out yet quite how this work should happen. In particular, I haven't figured out how to even specify what workers do what, much less how to inspect what they are doing. So this is on hold, at least until I figure that out.

**Comment by dtran320** [comment]
Sounds like a good idea, esp. with Channels being officially adopted as part of the Django project: https://www.djangoproject.com/weblog/2016/sep/09/channels-adopted-official-django-project/

Will try to find time to pitch in as we look into Channels ourselves!

**Comment by ryanhiebert** [comment]
I'm open to adding Channels support to this package, but I don't have any plans to get around to it any time soon. If someone comes along that would like to implement it, you've got my support!
