### ISSUE TITLE
Issue setting up HireFire with Django

### ISSUE THREAD

**Issue by miken** [ryanhiebert/hirefire#2]
Hi,

I followed your instructions to set up HireFire with my Django application: https://hirefire.readthedocs.org/en/latest/

Here's what my Procfile looks like: 
web: newrelic-admin run-program gunicorn catacombs.wsgi 
worker: newrelic-admin run-python manage.py rqworker high

I followed through steps 1-5 but when I started the server locally with "foreman start" and then browse to "http://localhost:8000/hirefire/test&quot;, I received an Internal Server Error message. When I checked the server log, it's a NoRedisConnectionException error. You can find more information from the error log here: https://gist.github.com/miken/23575952e204bc7fa11a

I also had Redis up and running locally. As you can see in my procfile, I'm also using Django-RQ to set up queues for RQ.

Do you have any advice for how I can troubleshoot this? I tried pushing to heroku but this didn't work either. Let me know.

Thanks, 
-Mike

**Comment by berinhard** [comment]
I ran into the same issue when trying to configure HireFire but using a other hostname and port for Redis. It would be nice if we can have a more complete example in the README or, at least, a link to this issue.

**Comment by azreda** [comment]
If you are using [django_redis](https://github.com/jazzband/django-redis) as a Redis cache backend, you can simplify to:

```python
from hirefire.procs.rq import RQProc
from django_redis import get_redis_connection

class WorkerProc(RQProc):
    name = 'worker'
    queues = ['high', 'default', 'low']
    connection = get_redis_connection('default')
```
