### ISSUE TITLE
Celery proc times out using celery 4

### ISSUE THREAD

**Issue by mjtamlyn** [ryanhiebert/hirefire#34]
`CeleryProc.quantity(cache={})` is causing a timeout (30s+, causes a run process to hang indefinitely) when I've upgraded to celery 4. I don't understand enough about how it's accessing the queue to know why. I can provide more details about my setup if necessary.

**Comment by ryanhiebert** [comment]
That'd be helpful. In particular, are you using the `simple_queues` property on your procs? And approximately how many celery workers are you running? Each one does add some overhead, and I've not yet been able to get my production environment upgraded to Celery 4, for reasons no longer related to HireFire.

I'd also recommend turning on logging for the `hirefire` logger, at at least the warning level. There's an error condition with Celery 4 that you may be getting caught on. I don't see that it would cause timeouts, though, just incorrect results.

**Comment by mjtamlyn** [comment]
I'm not using `simple_queues`, but it didn't make any difference when I set it true.

I have two queues declared on the Proc. The exact number of workers varies (obvs), but at present I have 3 dynos.

I'm using RabbitMQ as the message layer, with CloudAMQP.

The call to `quantity()` works just fine, it's only the cache code in `inspect_count` that fails.

```
Hirefire==0.5
Celery==4.0.2
```

Maybe I should try digging down a bit further and see where it starts hanging

**Comment by ryanhiebert** [comment]
That would also be helpful. There are 4 inspect calls that are made by default (the way you've got it set up). One to each of `active_queues` (to figure out which queues are running), `active`, `reserved`, and `scheduled`. These take a while, but in my experiment with Celery 4 weren't causing timeouts. I expect that the amount of time it takes to make those calls increases as the number of dynos increases, since it has to query more workers. At such a low number of dynos, it definitely surprises me that it's timing out, though I pretty much always expect it to be slow.

**Comment by ryanhiebert** [comment]
All of those calls happen here: https://github.com/ryanhiebert/hirefire/blob/master/hirefire/procs/celery.py#L49-L64

That might help you set breakpoints.

**Comment by mjtamlyn** [comment]
Ok, I'm making some progress. All of those possible inspect calls are failing, and failing in the same way. A more minimal case to get the failure is:

```
from celery.app import app_or_default
app = app_or_default()
app.control.inspect().active()
```

Using python's trace module, I've discovered that it's hanging in the threading module, at line 340, `waiter.acquire()`. Googling around the problem, it appears that this can occasionally happen in various ways when using the threading module. It's almost certainly nothing to do with hirefire. I'm going to follow up with celery.

**Comment by ryanhiebert** [comment]
Thank you for looking into it. I'm following that issue, but it's definitely out of my wheelhouse to understand. If it turns out that it needs to come back here for further followup, feel free to re-open this issue.

**Comment by Rawgeek** [comment]
In Django setting `BROKER_POOL_LIMIT = 1` hangs `app.control.inspect().active()` when using with AMQP

**Comment by ryanhiebert** [comment]
Would you like to open a new issue, perhaps with a bit more of a test case to reproduce? I'm not immediately sure what the right approach to fixing that will be, since I don't immediately see the cause. Its a bit beyond what I currently recall of Celery's implementation.

**Comment by Rawgeek** [comment]
I just thought this could be useful to someone having similar issue.
As removing `BROKER_POOL_LIMIT = 1` fixed the issue mentioned here
