### ISSUE TITLE
manually trigger scaling

### ISSUE THREAD

**Issue by t-io** [ryanhiebert/hirefire#36]
Is there a way to manually trigger a scaling on hirefire?
I have a service which needs an immediate upscale after pressing a button. 
I checked the code for the django middleware but I'am not sure where exactly the request happens.

**Comment by ryanhiebert** [comment]
As far as I know, there's not. HireFire checks once per minute. For my own use-cases, task queues that require immediate processing are ones that I ensure that there is always at least 1 running.

You could scale up the heroku dyno manually (or via the Heroku platform API), and then it should stick when HireFire attempts to scale it up to the same during its minutely check. Does that sound workable to you?

**Comment by ryanhiebert** [comment]
As far as I can tell, I don't think there'll be anything to do for this in this package, so I'm going to close this issue. Feel free to continue the conversation here if you disagree, or if have any follow-up questions.

**Comment by t-io** [comment]
Thanks for the response. Unfortunately 1 dyno will not save me from drowning. I think I have to build a custom solution for this case and use the heroku api.
