### ISSUE TITLE
DjangoProcSerializer failing to call super __call__

### ISSUE THREAD

**Issue by kanli1984** [ryanhiebert/hirefire#46]
I'm having issue with release 0.6. It's failing on line `return super(DjangoProcSerializer, self).__call__(args) `. Based on quick research online it looks like base class `ProcSerializer` is old style python class and you can't call super from inherited class. The exception I'm getting is `super() argument 1 must be type, not classobj`. Is there way to work around this?

**Comment by ryanhiebert** [comment]
Thanks for the report. I think the right way to fix that is to make the `ProcSerializer` base class inherit from object. Would you like to make a pull request to do that?

**Comment by kanli1984** [comment]
Created pull request to make ProcSerializer inherit from object. Tested locally and seem to work fine.

**Comment by ryanhiebert** [comment]
Merged.
