### ISSUE TITLE
Warning: exchange, routing_key pair not found: ('', 'QUEUE_NAME')

### ISSUE THREAD

**Issue by chickahoona** [ryanhiebert/hirefire#56]
We are using hirefire to automatically scale celery workers on heroku. Everything works fine, yet we see massive amount of events like: "exchange, routing_key pair not found: ('', 'QUEUE_NAME')"

We have in total three queues (scheduled,celery,priority) and we see events for all three of them.

We tried to find the source of this message and found this: https://hirefire.readthedocs.io/en/stable/_modules/hirefire/procs/celery/ your python module that we are using to automatically scale events.

Just so you are aware of the amount of logs that this line is causing. We have about 80 Mio events per week in our log. About 64 mio of these events are `exchange, routing_key pair not found: ...`

We for sure can disable this warning by increasing the log level for the hirefire module but maybe there is a more "proper" fix to the problem.

**Comment by tspecht** [comment]
Also seeing this, seems like due to this some tasks that are currently in-progress on a worker are not being counted because of this.

**Comment by chickahoona** [comment]
We were able to solve our issue. A simple `simple_queues = True` and the error disappeared.
