### ISSUE TITLE
load_procs should warn rather than erroring if a proc with a duplicate name is loaded

### ISSUE THREAD

**Issue by FishmanL** [ryanhiebert/hirefire#59]
in particular my blueprint registration is idempotent in other ways, so it might be getting run twice -- any chance of a silent failure on load_procs?

**Comment by ryanhiebert** [comment]
I guess I'd probably be fine with a warning instead of an error. If I were looking at your code, I'd probably want to figure out why I need to register the procs multiple times, though. That seems less than ideal.

**Comment by ryanhiebert** [comment]
A pull request would be welcome. I'm unlikely to write this up myself.

**Comment by FishmanL** [comment]
Done!  (The short answer for idempotency is 'our blueprint registration is complicated and multipathed, and somewhere in there is a small bug that I do want to fix eventually')
